version: '3.8'

services:
  agendadb:
    image: mysql
    container_name: agendadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=agenda

  agendaphpmyadmin:
    image: phpmyadmin
    container_name: agendaphpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - agendadb

  agendaapi:
    build: .
    container_name: agendaapi
    ports:
      - 3000:3000
    depends_on:
      - agendadb
