openapi: 3.0.0
paths:
  /user/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      tags:
        - user
      summary: getDetail
      description: Este endpoint devuelve los detalles de un usuario
      responses:
        "200":
          description: Retorna un usuario.
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/User"
      security:
        - bearerAuth: []

  /user:
    post:
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      tags:
        - user
      summary: getDetail
      description: Este endpoint devuelve los detalles de un usuario
      responses:
        "200":
          description: Retorna un usuario.
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/User"
      security:
        - bearerAuth: []
